name: plutomc
version: '1.0.0'
main: top.plutomc.plutomc.PlutoMC
api-version: 1.13
authors: [ GerryYuu ]
commands:
  plutomc:
    description: management command
    permission: plutomc.cmd
permissions:
  plutomc:
    children:
      cmd:
        default: false